/**
 * Dohyo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Metrics } from './metrics';

/**
* A class to represent impact data based on upgrade.  Attributes ----------     energy (Metrics): The data for energy usage per fuel type.     emissions (Metrics): The data for emissions per fuel type.     cost (Metrics): The data for cost per fuel type.
*/
export class Impact {
    'energy': Metrics;
    'emissions': Metrics;
    'cost': Metrics;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "energy",
            "baseName": "energy",
            "type": "Metrics"
        },
        {
            "name": "emissions",
            "baseName": "emissions",
            "type": "Metrics"
        },
        {
            "name": "cost",
            "baseName": "cost",
            "type": "Metrics"
        }    ];

    static getAttributeTypeMap() {
        return Impact.attributeTypeMap;
    }
}

