/**
 * Dohyo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BuildingProfile } from './buildingProfile';
import { HeatingFuel } from './heatingFuel';
import { ValidUpgrade } from './validUpgrade';

/**
* A class representing the request body used to retrieve a building\'s profile.  Attributes ----------     upgrade: Building Upgrade     heating_fuel: Heating Fuel     building_profile: Building Profile
*/
export class RemProfileRequest {
    'upgrade': ValidUpgrade;
    'heatingFuel'?: HeatingFuel | null;
    'buildingProfile': BuildingProfile;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "upgrade",
            "baseName": "upgrade",
            "type": "ValidUpgrade"
        },
        {
            "name": "heatingFuel",
            "baseName": "heating_fuel",
            "type": "HeatingFuel"
        },
        {
            "name": "buildingProfile",
            "baseName": "building_profile",
            "type": "BuildingProfile"
        }    ];

    static getAttributeTypeMap() {
        return RemProfileRequest.attributeTypeMap;
    }
}

export namespace RemProfileRequest {
}
