/**
 * Residential Electrification Model API An API for REM, the Residential
 * Electrification Model.
 *
 * The version of the OpenAPI document: 1.3.0 Contact:
 * datascience@rewiringamerica.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/** Details on the samples used in the model. */
export class SamplingDetails {
  /** The number of samples used to compute the statistics. */
  "numSamples": number;
  /**
   * The number of samples that matched the building profile but for which the
   * chosen upgradewas not applicable, and were therefore excluded when
   * computing the statistics.
   */
  "numExcludedSamples": number;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "numSamples",
      baseName: "num_samples",
      type: "number",
    },
    {
      name: "numExcludedSamples",
      baseName: "num_excluded_samples",
      type: "number",
    },
  ];

  static getAttributeTypeMap() {
    return SamplingDetails.attributeTypeMap;
  }
}
