/**
 * Dohyo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FuelData } from './fuelData';
import { FuelDataRates } from './fuelDataRates';
import { Impact } from './impact';

/**
* A class to represent savings data.  Attributes ----------     baseline (Impact): The data if no upgrade is passed into the surrogate model.     upgrade (Impact): The data if an upgrade is passed into the surrogate model.     delta (Impact): The deltas if an upgrade is passed into the surrogate model.     rates (List[FuelData]): The cost/fuel unit rates for each fuel type.     emissions_factors (List[FuelData]): The kgCO2e/fuel unit rates for each fuel type.
*/
export class Savings {
    'baseline': Impact;
    'upgrade': Impact;
    'delta': Impact;
    'rates': Array<FuelDataRates>;
    'emissionsFactors': Array<FuelData>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "baseline",
            "baseName": "baseline",
            "type": "Impact"
        },
        {
            "name": "upgrade",
            "baseName": "upgrade",
            "type": "Impact"
        },
        {
            "name": "delta",
            "baseName": "delta",
            "type": "Impact"
        },
        {
            "name": "rates",
            "baseName": "rates",
            "type": "Array<FuelDataRates>"
        },
        {
            "name": "emissionsFactors",
            "baseName": "emissions_factors",
            "type": "Array<FuelData>"
        }    ];

    static getAttributeTypeMap() {
        return Savings.attributeTypeMap;
    }
}

