/**
 * Residential Electrification Model API An API for REM, the Residential
 * Electrification Model.
 *
 * The version of the OpenAPI document: 1.3.2 Contact:
 * datascience@rewiringamerica.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import { FuelRate } from "./fuelRate";
import { FuelSavings } from "./fuelSavings";
import { Quantity } from "./quantity";
import { SamplingDetails } from "./samplingDetails";

/**
 * Represents the impacts of an upgrade and additional details on how these were
 * computed. Additional details include the rates, emissions factors and number
 * of samples used to compute the impacts.
 */
export class Savings {
  /** A dictionary of results, one for each fuel type. */
  "fuelResults": { [key: string]: FuelSavings };
  /** A dictionary of rates used to compute the cost of consuming each fuel. */
  "rates": { [key: string]: Array<FuelRate> };
  /**
   * A dictionary of conversion factors used to compute the emissions from
   * each fuel.
   */
  "emissionsFactors": { [key: string]: Quantity };
  /** A dictionary describing the number of samples used in the model. */
  "samplingDetails": SamplingDetails;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "fuelResults",
      baseName: "fuel_results",
      type: "{ [key: string]: FuelSavings; }",
    },
    {
      name: "rates",
      baseName: "rates",
      type: "{ [key: string]: Array<FuelRate>; }",
    },
    {
      name: "emissionsFactors",
      baseName: "emissions_factors",
      type: "{ [key: string]: Quantity; }",
    },
    {
      name: "samplingDetails",
      baseName: "sampling_details",
      type: "SamplingDetails",
    },
  ];

  static getAttributeTypeMap() {
    return Savings.attributeTypeMap;
  }
}
