/**
 * Residential Electrification Model API An API for REM, the Residential
 * Electrification Model.
 *
 * The version of the OpenAPI document: 1.3.0 Contact:
 * datascience@rewiringamerica.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/**
 * Water heater fuel options. Note that we do not currently support "Other
 * Fuel".
 */
export enum WaterHeaterFuel {
  Electricity = <any>"electricity",
  FuelOil = <any>"fuel_oil",
  NaturalGas = <any>"natural_gas",
  Propane = <any>"propane",
}
